// #524: an icon per idea, so "climb the hill at viktoriapark" isn't the
// hang out (circles) icon. Each idea in flare-ideas.data.ts and
// flare-ideas.anywhere.data.ts names one of these keys; the glyphs live in
// components/icons.tsx (IDEA_ICONS), the only file that imports icons. An
// idea without a key shows its category's icon.

export const IDEA_ICON_KEYS = [
  "ball",
  "bank",
  "basket",
  "beer",
  "bike",
  "binoculars",
  "bird",
  "books",
  "bowl",
  "bread",
  "burger",
  "cake",
  "carrot",
  "check",
  "climb",
  "cocktail",
  "coffee",
  "couch",
  "dice",
  "disco",
  "evergreen",
  "film",
  "flower",
  "house",
  "ice-cream",
  "leaf",
  "mask-happy",
  "mic",
  "mountains",
  "music",
  "paint-brush",
  "ping-pong",
  "planet",
  "plant",
  "question",
  "run",
  "sneaker",
  "snowflake",
  "sparkle",
  "storefront",
  "sun-horizon",
  "swap",
  "swim",
  "tag",
  "tai-chi",
  "tree",
  "vinyl",
  "walk",
  "waves",
  "wind",
] as const

export type IdeaIconKey = (typeof IDEA_ICON_KEYS)[number]
